spring.application.name=AdminPanel

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.context-path=/api

spring.main.banner-mode=OFF
spring.devtools.restart.exclude=**/META-INF/**,**/banner.txt,**/org/springframework/**
spring.devtools.restart.enabled=true
server.error.include-message=ALWAYS
server.error.include-stacktrace=ALWAYS
logging.level.root=INFO
logging.level.org.springframework=INFO



# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
